### ISSUE TITLE
DumpConfig() will print out tokens

### ISSUE THREAD

**Issue by cecilialau6776** [CLIP-HPC/goslmailer#23]
As the title states, DumpConfig() will print out tokens, which might be a potential security risk. (it also has a line that prints out `msteams.name` specifically, which I don't think is necessary)

**Comment by pja237** [comment]
Dear Cecilia,

Thank you so much for your contributions, first I’d like to appologise for these very delayed responses. I’m in the middle of the move to another country and have very limited time and computer access so I’ll ask you for a little bit more patience until the end of this week, when the whole thing should be over and I’ll be able to contribute some meaningful feedback and testing. For now I’d just like to say I 100% agree with this issue, you’re right, it’s not the most security aware thing to do. It’s residue from very early stages of development where it was useful to have this data dumped.
We should rectify this in the next release alongside the slack connector you've created.
I'll leave this open and we'll fix this asap.

**Comment by cecilialau6776** [comment]
A solution would be to add a debug flag/config/command line param and only dump the config if it's true.

**Comment by pja237** [comment]
Done, i patched this with the config parameter. Default behavior remains, dumps are disabled unless explicitly asked for.
Although i would like to see see the logging story completely redone one day with some nice, structured logs, and some levels perhaps... and colors :laughing: 
Some things are just remnants of very early development and the run to have a working prototype, like the msteams.name line, probably not the last one left around.
