### ISSUE TITLE
Hardcoded binary paths fail in certain environments

### ISSUE THREAD

**Issue by tdido** [CLIP-HPC/goslmailer#3]
I'm testing goslmailer in my [slurm-gcp](https://github.com/schedmd/slurm-gcp)-based cluster. The system setup differs from the one you've used to develop goslmailer, and therefore some hardcoded paths can't be found causing (somewhat) silent failures.

I've successfully generated an email from a job by changing the following lines to fit my environment:

- https://github.com/CLIP-HPC/goslmailer/blob/5189f278eae40b4a74117a0afe40ee20fb9520de/internal/lookup/lookup.go#L24
- https://github.com/CLIP-HPC/goslmailer/blob/5189f278eae40b4a74117a0afe40ee20fb9520de/internal/slurmjob/sacct.go#L227
- https://github.com/CLIP-HPC/goslmailer/blob/5189f278eae40b4a74117a0afe40ee20fb9520de/internal/slurmjob/sacct.go#L237

I'd be happy to work on an PR if you'd let me know what'd be your preferred way to make these paths configurable.

**Comment by pja237** [comment]
Hey,
thanks for the pointers on "how-not-to-write-code" :smile: and the offer to do PR :+1: 
Much appreciated.

I guess the quickest way to get rid of this legacy hardcoding might be to add new global vars for these binaries in the global section of the config:

https://github.com/CLIP-HPC/goslmailer/blob/5189f278eae40b4a74117a0afe40ee20fb9520de/internal/config/config.go#L14

Perhaps setting some default values (like the ones hardcoded) if they're not specified.

Then pass ithem on down from the main 

https://github.com/CLIP-HPC/goslmailer/blob/5189f278eae40b4a74117a0afe40ee20fb9520de/cmd/goslmailer/goslmailer.go#L65

The lookup one you can also avoid if you don't need it by specifying useLookup: "no" in conf to avoid the getent (quick one) but that should also be propagated from config. 

Of course, if you find any better/more elegant way, we're 100% open for suggestions.
How does it sound?

**Comment by pja237** [comment]
@tdido  Thank you for doing the fix for this :+1: 
I'll add one more PR today and then push a new version out with both.
