### ISSUE TITLE
Would you be able to add a license to this? 

### ISSUE THREAD

**Issue by rumiah-safe** [CLIP-HPC/goslmailer#36]
My team is hesitant to use this tool when the license isn't listed. The MIT license seems to align with your intentions for the project, but any license would be appreciated so we can know how you would like your work referenced and modified.

**Comment by ppm1337** [comment]
Please, if you want others to use/contribute to your seemingly great software, add a license to it. Your GO SlurmCommander is released under MIT, why not goslmailer?

**Comment by timeu** [comment]
I guess it makes sense. 
We will discuss this internally and respond next week.
